name: Build Addon Zip

on:
  push:
    tags:
      - "v*"

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir -p package/MWDInvite
          rsync -av --exclude ".git" --exclude ".github" --exclude "dist" ./ package/MWDInvite/
          cd package
          zip -r ../MWDInvite-${GITHUB_REF_NAME}.zip MWDInvite

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MWDInvite-${{ github.ref_name }}
          path: MWDInvite-${{ github.ref_name }}.zip
